Update use-releases-file-to-packaging.yml

diff --git a/.github/workflows/use-releases-file-to-packaging.yml b/.github/workflows/use-releases-file-to-packaging.yml
--- a/.github/workflows/use-releases-file-to-packaging.yml
+++ b/.github/workflows/use-releases-file-to-packaging.yml
@@ -270,59 +270,59 @@ jobs:
           sudo chown -R runner.runner /builder
           df -Th
 
-      - name: Download OpenWrt [ ${{ inputs.source_branch }} ]
-        id: down
-        working-directory: /builder
-        if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
-        run: |
-          # Set up compilation source code
-          if [[ "${{ inputs.source_branch }}" == *"official"* ]]; then
-              REPO_URL="https://github.com/openwrt/openwrt"
-              REPO_BRANCH="main"
-              TAGS_NAME="official"
-          elif [[ "${{ inputs.source_branch }}" == *"lede"* ]]; then
-              REPO_URL="https://github.com/coolsnowwolf/lede"
-              REPO_BRANCH="master"
-              TAGS_NAME="lede"
-          elif [[ "${{ inputs.source_branch }}" == *"immortalwrt"* ]]; then
-              REPO_URL="https://github.com/immortalwrt/immortalwrt"
-              REPO_BRANCH="master"
-              TAGS_NAME="immortalwrt"
-          else
-              echo "Unknown source code repository."
-              exit 1
-          fi
-
-          armvirt_tarfile_path="openwrt/output"
-          [[ -d "${armvirt_tarfile_path}" ]] || mkdir -p ${armvirt_tarfile_path}
-          ln -sf /builder/openwrt ${GITHUB_WORKSPACE}/openwrt
-          ln -sf /builder/openwrt /home/runner/work/_actions/davidonssv/amlogic-s9xxx-openwrt/main/openwrt
-
-          latest_version="$(curl -s \
-                              -H "Accept: application/vnd.github+json" \
-                              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-                              https://api.github.com/repos/${GITHUB_REPOSITORY}/releases?per_page=100 |
-                              jq '.[]' |
-                              jq -s --arg RTK "OpenWrt_${{ inputs.source_branch }}_" '.[] | select(.tag_name | contains($RTK))' |
-                              jq -s '.[].assets[] | {data:.updated_at, url:.browser_download_url}' |
-                              jq -s --arg BOARD "-rootfs.tar.gz" '.[] | select(.url | endswith($BOARD))' |
-                              jq -s 'sort_by(.data)|reverse[]' |
-                              jq -s '.[0]' -c
-                          )"
-
-          [[ "${latest_version}" == "null" ]] && echo "Invalid OpenWrt rootfs download address." && exit 1
-          latest_updated_at="$(echo ${latest_version} | jq -r '.data')"
-          latest_url="$(echo ${latest_version} | jq -r '.url')"
-
-          openwrt_filename="${latest_url##*/}"
-          curl -fsSL "${latest_url}" -o "${armvirt_tarfile_path}/${openwrt_filename}"
-          [[ "${?}" -ne "0" ]] && echo "Invalid OpenWrt rootfs download address." && exit 1
-
-          echo "build_tag=OpenWrt_${{ inputs.source_branch }}_${{ inputs.openwrt_storage }}_$(date +"%Y.%m")" >> ${GITHUB_OUTPUT}
-          df -hT ${PWD}
-          echo "REPO_URL=${REPO_URL}" >> ${GITHUB_OUTPUT}
-          echo "TAGS_NAME=${TAGS_NAME}" >> ${GITHUB_OUTPUT}
-          echo "status=success" >> ${GITHUB_OUTPUT}
+#      - name: Download OpenWrt [ ${{ inputs.source_branch }} ]
+#        id: down
+#        working-directory: /builder
+#        if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
+#        run: |
+#          # Set up compilation source code
+#          if [[ "${{ inputs.source_branch }}" == *"official"* ]]; then
+#              REPO_URL="https://github.com/openwrt/openwrt"
+#              REPO_BRANCH="main"
+#              TAGS_NAME="official"
+#          elif [[ "${{ inputs.source_branch }}" == *"lede"* ]]; then
+#              REPO_URL="https://github.com/coolsnowwolf/lede"
+#              REPO_BRANCH="master"
+#              TAGS_NAME="lede"
+#          elif [[ "${{ inputs.source_branch }}" == *"immortalwrt"* ]]; then
+#              REPO_URL="https://github.com/immortalwrt/immortalwrt"
+#              REPO_BRANCH="master"
+#              TAGS_NAME="immortalwrt"
+#          else
+#              echo "Unknown source code repository."
+#              exit 1
+#          fi
+#
+#          armvirt_tarfile_path="openwrt/output"
+#          [[ -d "${armvirt_tarfile_path}" ]] || mkdir -p ${armvirt_tarfile_path}
+#          ln -sf /builder/openwrt ${GITHUB_WORKSPACE}/openwrt
+#          ln -sf /builder/openwrt /home/runner/work/_actions/davidonssv/amlogic-s9xxx-openwrt/main/openwrt
+#
+#          latest_version="$(curl -s \
+#                              -H "Accept: application/vnd.github+json" \
+#                              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+#                              https://api.github.com/repos/${GITHUB_REPOSITORY}/releases?per_page=100 |
+#                              jq '.[]' |
+#                              jq -s --arg RTK "OpenWrt_${{ inputs.source_branch }}_" '.[] | select(.tag_name | contains($RTK))' |
+#                              jq -s '.[].assets[] | {data:.updated_at, url:.browser_download_url}' |
+#                              jq -s --arg BOARD "-rootfs.tar.gz" '.[] | select(.url | endswith($BOARD))' |
+#                              jq -s 'sort_by(.data)|reverse[]' |
+#                              jq -s '.[0]' -c
+#                          )"
+#
+#          [[ "${latest_version}" == "null" ]] && echo "Invalid OpenWrt rootfs download address." && exit 1
+#          latest_updated_at="$(echo ${latest_version} | jq -r '.data')"
+#          latest_url="$(echo ${latest_version} | jq -r '.url')"
+#
+#          openwrt_filename="${latest_url##*/}"
+#          curl -fsSL "${latest_url}" -o "${armvirt_tarfile_path}/${openwrt_filename}"
+#          [[ "${?}" -ne "0" ]] && echo "Invalid OpenWrt rootfs download address." && exit 1
+#
+#          echo "build_tag=OpenWrt_${{ inputs.source_branch }}_${{ inputs.openwrt_storage }}_$(date +"%Y.%m")" >> ${GITHUB_OUTPUT}
+#          df -hT ${PWD}
+#          echo "REPO_URL=${REPO_URL}" >> ${GITHUB_OUTPUT}
+#          echo "TAGS_NAME=${TAGS_NAME}" >> ${GITHUB_OUTPUT}
+#          echo "status=success" >> ${GITHUB_OUTPUT}
 
       - name: Packaging OpenWrt
         if: ${{ steps.down.outputs.status }} == 'success' && !cancelled()
